# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y

# Enable RGB underglow (also covers per-key RGB)
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=20
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=80
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=100
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100

# Enable external power (needed for nice!nano v2 to power LEDs via VCC)
CONFIG_ZMK_EXT_POWER=y